version: '2.1'
orbs:
  cypress: cypress-io/cypress@3.1.4
    
workflows:
  use-my-orb:
    jobs:
      run-tests:
        steps:
          - cypress/run-tests:
              cypress-command: npx cypress run  
              install-browsers: true
          - run: node ./scripts/zipScript.js        
          - store_artifacts:
              path: cypress/reports/mochawesome-report/report.zip    