version: '2.1'
orbs:
  cypress: cypress-io/cypress@3.1.4
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: | 
             npx cypress run  
             node ./scripts/zipScript.js
          install-browsers: true        
          post-steps:
            - store_artifacts:
                path: cypress/reports/mochawesome-report 