version: '2.1'
orbs:
  cypress: cypress-io/cypress@3.1.4
    
jobs:
  - cypress/run:
       cypress-command: npx cypress run  # Run Cypress tests
             
workflows:
  version: 2
  use-my-orb:
    jobs:
      - cypress-run
                                