version: 2.1
executors:
  # Define a custom executor that includes the Cypress image and the OpenJDK service container
  cypress-executor:
    docker:
      - image: cypress/browsers:latest  # Primary container with Cypress and browsers
    
jobs:
  build:
    executor: cypress-executor
    steps:
      - checkout  # Checkout the repository code    
      - run:
          name: Run Cypress Tests
          command: |
              npm install --legacy-peer-deps  # Install dependencies if needed           
              npx cypress run || true
      - run:
          name: Move Videos and Screenshots to Separate Directories
          command: |
            mkdir -p ./artifacts/videos                         
            mkdir -p ./artifacts/screenshots                    
            mv cypress/reports/mochawesome-report/TestReport/videos/* ./artifacts/videos/  
            mv cypress/reports/mochawesome-report/TestReport/screenshots/* ./artifacts/screenshots/  
      # Additional commands to zip reports, etc.
      - run:
          name: Zip  Report
          command: |
              node ./scripts/zipScript.js
              ls -l cypress/reports/mochawesome-report      
      - store_artifacts:
          path: ./artifacts/videos  # Store videos as artifacts
          destination: videos  # The artifact folder name in the CircleCI UI
      - store_artifacts:
          path: ./artifacts/screenshots  # Store screenshots as artifacts
          destination: screenshots  # The artifact folder name in the CircleCI UI

workflows:
  version: 2
  report:
    jobs:
      - build
