version: '2.1'
orbs:
  cypress: cypress-io/cypress@3.1.4
    
workflows:
  use-my-orb:
    jobs:  
        - cypress/run:
            cypress-command: npx cypress run  
            install-browsers: true
            start-command: node ./scripts/zipScript.js
            post-steps:
              - run: ls
              - store_artifacts:
                  path: cypress/reports/mochawesome-report/report.zip  
         