version: '2.1'
orbs:
  cypress: cypress-io/cypress@3.1.4
    
jobs:
    cypress-run:
      executor: cypress/default  # Docker image with Cypress and browsers
      steps:
        - checkout  # Check out the code from the repo
        - cypress/install  # Install Cypress dependencies
        - cypress/run:
            cypress-command: npx cypress run  # Run Cypress tests
             
workflows:
  version: 2
  use-my-orb:
    jobs:
      - cypress-run
                                