version: '2.1'
orbs:
  cypress: cypress-io/cypress@3.1.4
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run  
          install-browsers: true
          post-steps:
              - run: node ./scripts/zipScript.js
              - store_artifacts:
                  path: cypress/reports/mochawesome-report/report.zip     
      zip-report:
        docker:
            - image: node:16  # Use Node.js Docker image to run the zip script
        steps:      
            - run:
                name: Zip Report
                command: |
                   node ./scripts/zipScript.js  # Run the custom script to zip reports
                   ls -l cypress/reports/mochawesome-report            