version: 2.1

jobs:
  build:
    docker:
      # Primary container (browser image)
      - image: cypress/browsers:latest  # This image has Cypress and browsers, no Java
    steps:
      - checkout  # Checkout the repository code

      # Step 1: Install dependencies and ensure Java is available
      - run:
          name: Install Java
          command: |
            apt-get update && apt-get install -y openjdk-11-jdk  # Install Java in the main container

      - run:
          name: Check Java Version
          command: |
            java -version  # Verifies if Java is installed

workflows:
  version: 2
  build:
    jobs:
     
