version: 2.1

executors:
  node-executor:
    docker:
      - image: cypress/browsers:latest # Cypress Docker image with Node.js and browsers

jobs:
  build:
    executor: node-executor
    steps:
      - checkout  # Checkout the code from your GitHub repo

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps

      # Run Cypress tests
      - run:
          name: Run Cypress Tests
          command: npx cypress run 

      # Store Cypress test videos as artifacts
      - store_artifacts:
          path: /root/project/cypress/results/videos  # Path where Cypress stores videos
          destination: cypress-videos  # The name that will be shown in CircleCI's Artifacts tab

      - store_artifacts:
          path: /root/project/cypress/results/screenshots  
          destination: cypress-screenshots 

      - store_artifacts:
          path: /root/project/cypress/results/index.html  # Path where Cypress test results are stored
          destination: cypress-test-results        

workflows:
  version: 2
  test:
    jobs:
      - build  # Run the build job, which includes running Cypress and storing artifacts
