version: 2.1
executors:
  # Define a custom executor that includes the Cypress image and the OpenJDK service container
  cypress-executor:
    docker:
      - image: cypress/browsers:latest  # Primary container with Cypress and browsers
    
jobs:
  build:
    executor: cypress-executor
    steps:
      - checkout  # Checkout the repository code    
      - run:
          name: Run Cypress Tests
          command: |
              npm install --legacy-peer-deps  # Install dependencies if needed           
              npx cypress run || true     
      # Additional commands to zip reports, etc.
      - run:
          name: Zip  Report
          command: |
              node ./scripts/zipScript.js
              ls -l cypress/reports/mochawesome-report      
      - store_artifacts:
          path: cypress/reports/mochawesome-report/report.zip  
          destination: TestReport        
workflows:
  version: 2
  report:
    jobs:
      - build
