version: 2.1
executors:
  # Define a custom executor that includes the Cypress image and the OpenJDK service container
  cypress-executor:
    docker:
      - image: cypress/browsers:latest  # Primary container with Cypress and browsers
    
jobs:
  build:
    executor: cypress-executor
    steps:
      - checkout  # Checkout the repository code
     
      - run:
          name: Run Cypress Tests
          command: |
              npm install --legacy-peer-deps  # Install dependencies if needed           
              npx cypress run

      # Additional commands to zip reports, etc.
      - run:
          name: Zip Allure Report
          command: |
              node ./scripts/zipScript.js
              ls -l cypress/reports/mochawesome-report  # Verify report files
              
      - store_artifacts:
          path: cypress/reports/mochawesome-report/TestReport  # Path where Cypress stores videos
          destination: cypress-report  # The name that will be shown in CircleCI's Artifacts tab        

workflows:
  version: 2
  report:
    jobs:
      - build
